# Generated by Django 6.1.1 on 2026-10-01 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chai_images/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ML', 'Masala Latte'), ('CL', 'Chai Latte'), ('TL', 'Turmeric Latte'), ('GL', 'Ginger Latte'), ('HL', 'Honey Latte'), ('OL', 'Oat Latte'), ('AL', 'Almond Latte'), ('CL', 'Coconut Latte'), ('SL', 'Spiced Latte')], max_length=2)),
            ],
        ),
    ]
